@startuml ServeurWeb

interface IServeurWeb {
     + repondre(RequeteHttp): int
}

class ServeurWeb 

class ServeurWebProxy {
     - serveurWeb: ServeurWeb
}

class RequeteHttp {
     + getUrl(): String
}
note right: Design Pattern Composite

interface Affichable {
     + afficher(): String
}

class Url {
     - path: String
     + Url(String)
}

class Header {
     - headers: Map<String, String>
     + ajouterHeader(String, String)
}

class Body {
     - content: String
     + Body(String)
}

RequeteHttp .up.> Affichable
Url .up.> Affichable
Header .up.> Affichable
Body .up.> Affichable

Url -down-* RequeteHttp: url
Header -down-* RequeteHttp: header
Body -down-* RequeteHttp: body
 
ServeurWeb <-right- ServeurWebProxy : use
ServeurWeb -up-|> IServeurWeb
ServeurWebProxy -up-|> IServeurWeb
note "Design Pattern Proxy" as NoteProxy
ServeurWebProxy .down. NoteProxy
ServeurWeb .down. NoteProxy

@enduml
